### ISSUE TITLE
A DTB value was found but failed to verify.

### ISSUE THREAD

**Issue by AndresZeng** [fireeye/rvmi#8] opened 2018-04-17 03:11 UTC
After I finished the whole installation, I tried the command:

> rekall -v -f win7.elf --profile ~/rekall-profiles/v1.0/nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942

(I had already made sure the profile's hash code.) and input the command:

> pslist

Then I received the debug logging as following:

andres@zyt:~/iso$ rekall -v -f win7.elf --profile ~/rekall-profiles/v1.0/nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942
2018-04-17 11:00:59,550:DEBUG:rekall.1:Logging level set to 10
2018-04-17 11:00:59,550:DEBUG:rekall.1:Opened local file /home/andres/rekall-profiles/v1.0/nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942.json
2018-04-17 11:01:07,522:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2018-04-17 11:01:08,015:DEBUG:rekall.1:Opened local file /home/andres/.rekall_cache/v1.0/inventory.gz
2018-04-17 11:01:11,850:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2018-04-17 11:01:12,522:DEBUG:rekall.1:Opened local file /home/andres/.rekall_cache/v1.0/inventory.gz
2018-04-17 11:01:12,522:DEBUG:rekall.1:Opened local file /home/andres/.rekall_cache/v1.0/nt/undocumented.gz
2018-04-17 11:01:12,826:INFO:rekall.1:Loaded profile nt/undocumented from Local Cache Directory:/home/andres/.rekall_cache (in 0.303564071655 sec)
2018-04-17 11:01:12,891:DEBUG:rekall.1:Voting round with base: None
2018-04-17 11:01:12,891:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-04-17 11:01:12,891:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-04-17 11:01:12,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-04-17 11:01:12,892:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-04-17 11:01:12,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-04-17 11:01:12,892:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-04-17 11:01:12,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-04-17 11:01:12,892:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-04-17 11:01:12,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-04-17 11:01:15,191:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-04-17 11:01:15,191:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-04-17 11:01:15,191:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-04-17 11:01:15,191:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-04-17 11:01:15,192:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-04-17 11:01:15,192:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-04-17 11:01:15,192:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-04-17 11:01:15,192:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-04-17 11:01:15,192:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-04-17 11:01:15,192:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-04-17 11:01:15,192:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-04-17 11:01:15,192:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-04-17 11:01:15,192:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-04-17 11:01:15,192:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-04-17 11:01:15,280:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-04-17 11:01:15,280:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-04-17 11:01:15,281:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at win7.elf_info
2018-04-17 11:01:15,281:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.qmp_as.QMPAddressSpace'> 
2018-04-17 11:01:15,281:DEBUG:rekall.1:Failed instantiating QMPAddressSpace: provided path does not point to a socket
2018-04-17 11:01:15,281:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-04-17 11:01:15,281:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-04-17 11:01:15,281:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-04-17 11:01:15,281:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-04-17 11:01:15,281:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-04-17 11:01:15,281:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-04-17 11:01:15,590:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xfb494651
2018-04-17 11:01:15,590:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-04-17 11:01:15,590:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-04-17 11:01:15,591:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-04-17 11:01:15,591:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.qmp_as.QMPAddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating QMPAddressSpace: must be first Address Space
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-04-17 11:01:15,592:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-04-17 11:01:15,592:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-04-17 11:01:18,115:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-04-17 11:01:18,116:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-04-17 11:01:18,116:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-04-17 11:01:18,116:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-04-17 11:01:18,116:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-04-17 11:01:18,116:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2018-04-17 11:01:18,117:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': '/home/andres/rekall-profiles/v1.0/nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942.json'})
2018-04-17 11:01:18,117:DEBUG:rekall.1:Opened local file /home/andres/rekall-profiles/v1.0/nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942.json
2018-04-17 11:01:18,259:DEBUG:rekall.1:Opened local file /home/andres/.rekall_cache/v1.0/nt/undocumented.gz
2018-04-17 11:01:18,260:INFO:rekall.1:Loaded profile nt/undocumented from Local Cache Directory:/home/andres/.rekall_cache (in 0.00091290473938 sec)

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.6.0 (Gotthard).
For the memory of a lifetime, now with rVMI 0.1 (Augustiner).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
Or https://github.com/fireeye for more info about rVMI.
----------------------------------------------------------------------------
[1] win7.elf 11:06:28> pslist
---------------------> pslist()
2018-04-17 11:06:28,998:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({})
2018-04-17 11:06:28,999:DEBUG:rekall.1:Opened local file /home/andres/.rekall_cache/v1.0/nt/eprocess_index.gz
2018-04-17 11:06:29,087:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/andres/.rekall_cache (in 0.0873560905457 sec)
2018-04-17 11:06:29,087:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-04-17 11:06:58,114:DEBUG:rekall.1:Found _EPROCESS @ 0xA799FA2C (DTB: 0x0)
2018-04-17 11:06:58,115:DEBUG:rekall.1:Found _EPROCESS @ 0xA7C03BDC (DTB: 0x4400490050)
2018-04-17 11:08:06,881:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
2018-04-17 11:08:06,881:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.

So I have no idea how to continue now.

**Comment by pfohjo** [comment] 2018-04-18 13:05
If I had to guess, I would guess the issue is with the memory image you are attempting to open.  This does not seem to be a rVMI issue as you are loading a file that is being handled as a "FileAddressSpace" by rekall.  Please follow the directions here: https://github.com/fireeye/rvmi/blob/master/README.md

I am closing this as it does not seem to be a rVMI issue.  Feel free to re-open if you have issues after following the README instructions.

**Closed as completed by pfohjo** 2018-04-18 13:05 UTC
